=== d19rarir/d19rarir.github.io/lm/vueltaMundo/viaje.dtd
<!ELEMENT viajes (viaje)>
<!ATTLIST viajes xmlns:xsi CDATA #IMPLIED>
<!ATTLIST viajes xsi:noNamespaceSchemaLocation CDATA #IMPLIED>
<!ELEMENT viaje (etapa*)>
<!ELEMENT etapa (ciudad_salida,ciudad_llegada,transporte*,precio,anecdota,descripcion,foto*,kml)>
<!ATTLIST etapa num CDATA #REQUIRED>
<!ATTLIST etapa fecha CDATA #REQUIRED>
<!ELEMENT ciudad_salida (#PCDATA)>
<!ELEMENT ciudad_llegada (#PCDATA)>
<!ELEMENT transporte (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT anecdota (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ELEMENT kml (#PCDATA)>

=== d19rarir/d19rarir.github.io/lm/vueltaMundo/viaje-completo.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD -->
<!DOCTYPE viajes SYSTEM "viaje.dtd">

<!-- XSLT -->
<?xml-stylesheet type="text/xsl" href="viaje.xsl"?>

<!-- Inicio del viaje -->
<viajes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="viaje.xsd">
    <viaje>

        <!-- Etapa 1 -->
        <etapa num="1" fecha="07/03/2021">
            <ciudad_salida>Córdoba</ciudad_salida>
            <ciudad_llegada>Madrid</ciudad_llegada>
            <transporte>AVE</transporte>
            <precio>22</precio>
            <anecdota>Nada mejor que empezar una vuelta al mundo el dia de tu cumpleaños</anecdota>
            <descripcion>
                Primer día de esta aventura que acaba de comenzar. 7 de Marzo de 2021, ¿qué más se puede el día 
                de tu cumpleaños? Este viaje comienza camino a la capital de España, Madrid será el punto de partida 
                de este viaje alrededor del mundo. Será algo express porque no tenemos mucho tiempo pero si el 
                suficiente para que el viaje sea divertido. Nos desplazamos desde Córdoba a Madrid en AVE, una vez
                allí pasamos el día visitando los lugares más conocidos de la ciudad, El Retiro, Gran Vía, Puerta del Sol
                y no olvidarnos de comer en TACOS a mi novia y a mi nos hacía mucha ilusión comer alli. No pudimos hacer
                mucho más porque al día siguiente nuestro vuelo a Sudáfrica salía temprano. Tocaba descansar. 
            </descripcion>
            <foto>./img/Madrid.jpg</foto>
        </etapa>

        <!-- Etapa 2 -->
        <etapa num="2" fecha="07/03/2021"> 
            <ciudad_salida>Madrid</ciudad_salida>
            <ciudad_llegada>Sudáfrica</ciudad_llegada>
            <transporte>Avión</transporte>
            <precio>22</precio>
            <anecdota>Visitar SoccerCity y revivir cuando fuimos campeones del mundo</anecdota>
            <descripcion></descripcion>
            <foto>./img/Sudáfrica.jpg</foto>
        </etapa>

        <!-- Etapa 3 -->
        <etapa num="3" fecha="07/03/2021">
            <ciudad_salida>Sudafrica</ciudad_salida>
            <ciudad_llegada>Zimbabwe</ciudad_llegada>
            <transporte></transporte>
            <precio>2</precio>
            <anecdota>Cataratas Victoria</anecdota>
            <descripcion></descripcion>
            <foto></foto>
        </etapa>
        
        <!-- Etapa 4 -->
        <etapa num="4" fecha="07/03/2021">
            <ciudad_salida>Sudafrica</ciudad_salida>
            <ciudad_llegada>Dubai</ciudad_llegada>
            <transporte>Avión</transporte>
            <precio>2</precio>
            <anecdota>Paracaidismo Palmeras</anecdota>
            <descripcion></descripcion>
            <foto></foto>
        </etapa>
      
        <!-- Etapa 5 -->
        <etapa num="5" fecha="07/03/2021">
            <ciudad_salida>Dubai</ciudad_salida>
            <ciudad_llegada>Nueva Zelanda</ciudad_llegada>
            <transporte>Avión</transporte>
            <precio>2</precio>
            <anecdota></anecdota>
            <descripcion></descripcion>
            <foto></foto>
        </etapa>

        <!-- Etapa 6 -->
        <etapa num="6" fecha="07/03/2021">
            <ciudad_salida>Nueva Zelanda</ciudad_salida>
            <ciudad_llegada>Los Angeles</ciudad_llegada>
            <transporte>Avión</transporte>
            <precio>2</precio>
            <anecdota>Staples Center y GTA</anecdota>
            <descripcion></descripcion>
            <foto></foto>
        </etapa>
        
        <!-- Etapa 7 -->
        <etapa num="7" fecha="07/03/2021">
            <ciudad_salida>Los Angeles</ciudad_salida>
            <ciudad_llegada>Peru</ciudad_llegada>
            <transporte>Avión</transporte>
            <precio>2</precio>
            <anecdota>MachuPichu</anecdota>
            <descripcion></descripcion>
            <foto></foto>
        </etapa>
        
        <!-- Etapa 8 -->
        <etapa num="8" fecha="07/03/2021">
            <ciudad_salida>Peru</ciudad_salida>
            <ciudad_llegada>Noruega</ciudad_llegada>
            <transporte>Avión</transporte>
            <precio>2</precio>
            <anecdota>Fiordos</anecdota>
            <descripcion></descripcion>
            <foto></foto>
        </etapa>
        
        <!-- Etapa 9 -->
        <etapa num="9" fecha="07/03/2021">
            <ciudad_salida>Noruega</ciudad_salida>
            <ciudad_llegada>Londres</ciudad_llegada>
            <transporte>Avión</transporte>
            <precio>2</precio>
            <anecdota>El puente</anecdota>
            <descripcion></descripcion>
            <foto></foto>
        </etapa>
        
        <!-- Etapa 10 -->
        <etapa num="10" fecha="07/03/2021">
            <ciudad_salida>Londres</ciudad_salida>
            <ciudad_llegada>Barcelona</ciudad_llegada>
            <transporte>Avión</transporte>
            <precio>2</precio>
            <anecdota>Camp Nou y Monumentos</anecdota>
            <descripcion></descripcion>
            <foto></foto>
        </etapa>
        
        <!-- Etapa 11 -->
        <etapa num="11" fecha="07/03/2021">
            <ciudad_salida>Barcelona</ciudad_salida>
            <ciudad_llegada>Cordoba</ciudad_llegada>
            <transporte>AVE</transporte>
            <precio>2</precio>
            <anecdota>Calor xD</anecdota>
            <descripcion></descripcion>
            <foto></foto>
        </etapa>
        
    </viaje>
</viajes>

=== d19rarir/d19rarir.github.io/lm/vueltaMundo/viaje.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD -->
<!DOCTYPE viajes SYSTEM "viaje.dtd">

<!-- XSLT -->
<?xml-stylesheet type="text/xsl" href="viaje.xsl"?>

<!-- Inicio del viaje -->
<viajes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="viaje.xsd">
    <viaje>

        <!-- Etapa 1 -->
        <etapa num="1" fecha="07/03/2021">
            <ciudad_salida>Córdoba</ciudad_salida>
            <ciudad_llegada>Madrid</ciudad_llegada>
            <transporte>AVE</transporte>
            <precio>22</precio>
            <anecdota>Nada mejor que empezar una vuelta al mundo el dia de tu cumpleaños</anecdota>
            <descripcion>
                Primer día de esta aventura que acaba de comenzar. 7 de Marzo de 2021, ¿qué más se puede el día 
                de tu cumpleaños? Este viaje comienza camino a la capital de España, Madrid será el punto de partida 
                de este viaje alrededor del mundo. Será algo express porque no tenemos mucho tiempo pero si el 
                suficiente para que el viaje sea divertido. Nos desplazamos desde Córdoba a Madrid en AVE, una vez
                allí pasamos el día visitando los lugares más conocidos de la ciudad, El Retiro, Gran Vía, Puerta del Sol
                y no olvidarnos de comer en Tierra Burritos a mi novia y a mi nos hacía mucha ilusión comer alli. No pudimos hacer
                mucho más porque al día siguiente nuestro vuelo a Sudáfrica salía temprano. Tocaba descansar. 
            </descripcion>
            <foto>./img/Madrid.jpg</foto>
            <kml>https://www.google.com/maps/d/u/0/embed?mid=1oGHNCJN3-GWmj_sPt5xo15T5TFOaOM_c</kml>
        </etapa>

    </viaje>
</viajes>
