=== d19rarir/d19rarir.github.io/lm/tema7/RamirezRiveraRuben/ejercicio2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="rrhh">
        <xs:complexType>
            <xs:sequence>
                <xs:element name = "curriculum" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="datosPersonales" type="personal"/>
                            <xs:element name="datosAcademicos" type="academico"/>
                            <xs:element name="experienciaLaboral" type="laboral" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
                        <xs:attribute name="presentacion" type="xs:date" use="required"/>
                        <xs:attribute name="categoria" type="xs:string" default="desarrollador" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="personal">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string"/>
            <xs:element name="apellido1" type="xs:string"/>
            <xs:element name="apellido2" type="xs:string"/>
            <xs:element name="correoElectronico" type="xs:string"/>
            <xs:element name="direccion" maxOccurs="2">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="calle" type="xs:string"/>
                        <xs:element name="localidad" type="xs:string" default="Cordoba"/>
                        <xs:element name="codigoPostal" type="xs:positiveInteger"/>
                        <xs:element name="provincia" type="xs:string" default="Cordoba"/>
                        <xs:element name="pais" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="redesSociales" maxOccurs="5">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nombre" type="xs:string"/>
                        <xs:element name="nick" type="xs:string"/>
                        <xs:element name="enlace" type="xs:string"/>
                        <xs:element name="valoracion">
                            <xs:simpleType>
                                <xs:restriction base="xs:positiveInteger">
                                    <xs:minInclusive value="1"/>
                                    <xs:maxInclusive value="5"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="academico">
        <xs:sequence>
            <xs:element name="titulacionOficial">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="descripcion" type="xs:string"/>
                        <xs:element name="organimosResposable" type="xs:string"/>
                        <xs:element name="fechaInicio" type="xs:date"/>
                        <xs:element name="fechaFin" type="xs:date"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="cursos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="descripcion" type="xs:string"/>
                        <xs:element name="empresaResponsable" type="xs:string"/>
                        <xs:element name="fechaInicio" type="xs:date"/>
                        <xs:element name="fechaFin" type="xs:date"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="nivelIdioma" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="idioma" type="xs:string"/>
                        <xs:element name="comprender" type="level"/>
                        <xs:element name="hablar" type="level"/>
                        <xs:element name="escribir" type="level"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="laboral">
        <xs:sequence>
            <xs:element name="empresa" type="xs:string"/>
            <xs:element name="fecha" type="xs:date"/>
            <xs:element name="desempeÃ±o" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="level">
        <xs:restriction base="xs:string">
            <xs:enumeration value="A1"/>
            <xs:enumeration value="A2"/>
            <xs:enumeration value="B1"/>
            <xs:enumeration value="B2"/>
            <xs:enumeration value="C1"/>
            <xs:enumeration value="C2"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== d19rarir/d19rarir.github.io/lm/tema7/RamirezRiveraRuben/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<rrhh xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="ejercicio2.xsd">
    <curriculum id="1" presentacion="2020-03-23" categoria="desarrollador">
        <datosPersonales>
            <nombre>Ruben</nombre>
            <apellido1>Ramirez</apellido1>
            <apellido2>Rivera</apellido2>
            <correoElectronico>ruben@gmail.com</correoElectronico>
            <direccion>
                <calle>Mi casa</calle>
                <localidad>Cordoba</localidad>
                <codigoPostal></codigoPostal>
                <provincia>Cordoba</provincia>
                <pais>España</pais>
            </direccion>
            <redesSociales>
                <nombre>Ruben</nombre>
                <nick>rubensio</nick>
                <enlace>twitter.es/rubensio</enlace>
                <valoracion>2</valoracion>
            </redesSociales>
        </datosPersonales>
        <datosAcademicos>
            <titulacionOficial>
                <descripcion>DAW</descripcion>
                <organimosResposable>Junta Andalucia</organimosResposable>
                <fechaInicio>2019-10-03</fechaInicio>
                <fechaFin>2020-03-16</fechaFin>
            </titulacionOficial>
            <cursos>
                <descripcion>Programacion JAVA</descripcion>
                <empresaResponsable>Oracle</empresaResponsable>
                <fechaInicio>2019-10-03</fechaInicio>
                <fechaFin>2020-03-16</fechaFin>
            </cursos>
            <nivelIdioma>
                <idioma>Ingles</idioma>
                <comprender>B1</comprender>
                <hablar>B1</hablar>
                <escribir>B1</escribir>
            </nivelIdioma>
        </datosAcademicos>
        <experienciaLaboral>
            <empresa>Casa</empresa>
            <fecha>2019-06-20</fecha>
            <desempeño>Cajero</desempeño>
        </experienciaLaboral>
    </curriculum>
</rrhh>
